# Generated by Django 4.0.3 on 2022-05-22 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0002_alter_cloud_computing_language_info_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=50)),
                ('course_intro', models.CharField(max_length=500)),
                ('course_intro_link', models.CharField(max_length=50)),
                ('full_course_link', models.CharField(max_length=50)),
            ],
        ),
    ]
