# Generated by Django 4.0.3 on 2022-05-22 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0004_amazon_web_android_app_ios_app'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amazon_web',
            name='reference_link',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='android_app',
            name='reference_link',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='cloud_computing',
            name='reference_link',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='ios_app',
            name='reference_link',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='machine_learning',
            name='reference_link',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='software_testing',
            name='reference_link',
            field=models.CharField(max_length=200),
        ),
    ]
