# Generated by Django 4.0.3 on 2022-05-22 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0005_alter_amazon_web_reference_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='front_end',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=50)),
                ('language_info', models.CharField(max_length=500)),
                ('reference_link', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='full_stack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=50)),
                ('language_info', models.CharField(max_length=500)),
                ('reference_link', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameModel(
            old_name='amazon_Web',
            new_name='back_end',
        ),
    ]
